### ISSUE TITLE
diazo theme blocked

### ISSUE THREAD

**Issue by ginetsl** [mamico/experimental.noacquisition#1]
Hello,

I was testing this product on my plone site to block acquisition when requesting content on any of the subsites inside it. It does its work, but it also blocks access to the diazo theme and its resources.

My current setup:
Plone = 5.0.6
plone.app.theming = 1.3.0
* One plone site at the root, and subfolders with navigation root behavior applied. The root site and all the subsites use the same diazo theme (installed on the root site).

The plone site and each subsite have their own domain name, so they are accessed like this:

parentsite.com for the parent site
subsiteX.com for each parent/subfolder with navigation root behavior enabled

I currently have dryrun=True, and the warnings shown on the logs are of the form:

`WARNING experimental.noacquisition traverse without explicit acquisition object=<Folder at /parent/subsite> name='parent' subobject=<PloneSite at /parent used for /parent/subsite> url='http://subsite.com/parent/++theme++mytheme/images/favicon.ico' referer=''`

If I set dryrun to False I get totally unthemed pages for the parent and any of the subsites.

My apologies if this is not clear enough or if I am missing important details. I'd be more than happy to provide more information/explanations.

Thank you,

Ginet

**Comment by mamico** [comment]
I think that there is a problem somewhere in (your?) diazo theme, because the right favicon.ico url (and other theme resources) must be http://subsite.com/++theme++mytheme/images/favicon.ico without "/parent" 

I tried a Vanilla Plone 5.0.6 site with default diazo theme and I can't reproduce your problem.

Hint: check your "Absolute path prefix" on @@theming-controlpanel "advance settings" tab, if there is something different than /++theme++mytheme proably that the problem is here...

**Comment by ginetsl** [comment]
probably related to my apache rule being applied to the requests for theme resources:

`RewriteRule ^(/.*)?$ http://127.0.0.1:XXXXX/VirtualHostBase/http/subsite.com:80/parent/subsite/VirtualHostRoot$1 [L,P]`

I need that rule for my VH configuration to work, so I don't know if I can make something else work :-(

Ginet

**Comment by mamico** [comment]
Nope. The apache rule seems correct to me...

**Comment by ginetsl** [comment]
The absolute path prefix in my theme is correct ( /++theme++mytheme ).

**Comment by mamico** [comment]
As a workaround you could try to replace apache rule with **something** like

```
RewriteRule ^/+parent(/\+\+theme\+\+.*) $1
RewriteRule ^(/.*)?$ http://127.0.0.1:XXXXX/VirtualHostBase/http/subsite.com:80/parent/subsite/VirtualHostRoot$1 [L,P]
```

or

`RewriteRule ^(/+parent)?(/.*)?$ http://127.0.0.1:XXXXX/VirtualHostBase/http/subsite.com:80/parent/subsite/VirtualHostRoot$2 [L,P]`

but IMO the problem is not related to experimental.noacquisition: the url http://subsite.com/parent/++theme++mytheme/images/favicon.ico is wrong and correctly catched. (sorry)

**Comment by ginetsl** [comment]
You are correct, the problem is not caused by experimental.noacquisition. This issue can be closed.

Thank you!!

**Comment by mamico** [comment]
you are welcome!
